// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHQNyK5PSEKwfqTDrI78u7X7iDZdaqnPo',
    appId: '1:216789899738:web:6a849254862d5bee9708e3',
    messagingSenderId: '216789899738',
    projectId: 'touch-app-f585b',
    authDomain: 'touch-app-f585b.firebaseapp.com',
    storageBucket: 'touch-app-f585b.appspot.com',
    measurementId: 'G-YQWFJPH321',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6WG4LKBClSaQv5M02-zpRSLEnO7g-HDA',
    appId: '1:216789899738:android:4e936bbb4e192f819708e3',
    messagingSenderId: '216789899738',
    projectId: 'touch-app-f585b',
    storageBucket: 'touch-app-f585b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHX1U1Az4SKKq-phr6dfSy1FfZhHGC3tc',
    appId: '1:216789899738:ios:bb6494405afdb4919708e3',
    messagingSenderId: '216789899738',
    projectId: 'touch-app-f585b',
    storageBucket: 'touch-app-f585b.appspot.com',
    iosClientId: '216789899738-6k8mhtq4solavulknsh8vod9h957rn4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.touch',
  );
}
